"""Initial migration

Revision ID: 8b7f7a3d9829
Revises: 
Create Date: 2022-01-27 12:34:22.769666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7f7a3d9829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('moderator', sa.Boolean(), nullable=True),
    sa.Column('pen_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_table('authorhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorhistory_id'), 'authorhistory', ['id'], unique=False)
    op.create_table('authorstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automatic_books_published', sa.Integer(), nullable=True),
    sa.Column('automatic_words_written', sa.Integer(), nullable=True),
    sa.Column('books_read', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('manual_books_published', sa.Integer(), nullable=True),
    sa.Column('manual_words_written', sa.Integer(), nullable=True),
    sa.Column('needs_food', sa.Boolean(), nullable=True),
    sa.Column('needs_hygiene', sa.Boolean(), nullable=True),
    sa.Column('needs_sleep', sa.Boolean(), nullable=True),
    sa.Column('needs_to_read', sa.Boolean(), nullable=True),
    sa.Column('needs_to_relax', sa.Boolean(), nullable=True),
    sa.Column('needs_to_research', sa.Boolean(), nullable=True),
    sa.Column('time_spent_eating', sa.Integer(), nullable=True),
    sa.Column('time_spent_hygiene', sa.Integer(), nullable=True),
    sa.Column('time_spent_reading', sa.Integer(), nullable=True),
    sa.Column('time_spent_relaxing', sa.Integer(), nullable=True),
    sa.Column('time_spent_researching', sa.Integer(), nullable=True),
    sa.Column('time_spent_sleeping', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('writers_block', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorstatus_id'), 'authorstatus', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorstatus_id'), table_name='authorstatus')
    op.drop_table('authorstatus')
    op.drop_index(op.f('ix_authorhistory_id'), table_name='authorhistory')
    op.drop_table('authorhistory')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
